Before cleaning or analyzing anything, we need to answer:
"What data do we have, and can we trust it?"

This notebook is about understanding, not changing, the data.

In [7]:
#Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#lets set the display options
pd.set_option('display.max_columns', None)
customer_df = pd.read_csv('../data/customer_data.csv')
transactions_df = pd.read_csv('../data/transactions_data.csv')

Lets try and understand the structure of the data before looking at any values

In [9]:
print("-"*50)
print("Customer Data")
print("-"*50)

print(f"Rows:{customer_df.shape[0]}")
print(f"Columns:{customer_df.shape[1]}")

--------------------------------------------------
Customer Data
--------------------------------------------------
Rows:48723
Columns:54

In [2]:
customer_df.head()

,customer_id,age,gender,location,income_bracket,occupation,education_level,marital_status,household_size,acquisition_channel,...,total_transaction_volume,transaction_frequency,last_transaction_date,preferred_transaction_type,first_transaction_date,weekend_transaction_ratio,avg_daily_transactions,customer_tenure,churn_probability,customer_lifetime_value
0,93716481,44,Male,"Pereira, Risaralda",Very High,Engineer,Master,Married,5,Partnership,...,60540250,0.030769,2023-12-05,Transfer,2023-01-05,0.300000,0.030769,11.633333,0.362269,3.124148e+08
1,49020929,44,Male,"Cali, Valle del Cauca",Medium,Construction Worker,Bachelor,Married,2,Paid Ad,...,23401550,0.032934,2023-12-18,Transfer,2023-02-05,0.181818,0.032934,11.500000,0.181790,1.670223e+08
2,52690950,45,Male,"Barranquilla, Atlántico",High,Construction Worker,Bachelor,Married,4,Paid Ad,...,35759150,0.050000,2023-10-27,Transfer,2023-01-31,0.300000,0.050000,8.766667,0.321265,1.940371e+07
3,23199751,45,Male,"Bogotá, Cundinamarca",High,Electrician,High School,Single,2,Referral,...,21186950,0.047782,2023-11-30,Transfer,2023-01-10,0.142857,0.047782,10.733333,0.336629,3.597811e+07
4,61997066,44,Female,"Bogotá, Cundinamarca",Medium,Cleaner,Bachelor,Married,3,Paid Ad,...,11640800,0.061889,2023-11-17,Payment,2023-01-05,0.315789,0.061889,11.633333,0.398151,3.046620e+08

In [4]:
transactions_df.head()

   customer_id        date   amount        type
0     93716481  2023-11-23  1262800    Transfer
1     93716481  2023-01-05   928900  Withdrawal
2     93716481  2023-11-05  1683100     Payment
3     93716481  2023-04-14  4507350     Payment
4     93716481  2023-08-04  2096150     Payment

In [5]:
customer_df.columns

Index(['customer_id', 'age', 'gender', 'location', 'income_bracket',
       'occupation', 'education_level', 'marital_status', 'household_size',
       'acquisition_channel', 'customer_segment', 'savings_account',
       'credit_card', 'personal_loan', 'investment_account',
       'insurance_product', 'active_products', 'app_logins_frequency',
       'feature_usage_diversity', 'bill_payment_user', 'auto_savings_enabled',
       'credit_utilization_ratio', 'international_transactions',
       'failed_transactions', 'tx_count', 'avg_tx_value', 'total_tx_volume',
       'first_tx', 'last_tx', 'base_satisfaction', 'tx_satisfaction',
       'product_satisfaction', 'satisfaction_score', 'nps_score',
       'last_survey_date', 'support_tickets_count', 'resolved_tickets_ratio',
       'app_store_rating', 'feedback_sentiment', 'feature_requests',
       'complaint_topics', 'clv_segment', 'monthly_transaction_count',
       'average_transaction_value', 'total_transaction_volume',
       'transaction_frequency', 'last_transaction_date',
       'preferred_transaction_type', 'first_transaction_date',
       'weekend_transaction_ratio', 'avg_daily_transactions',
       'customer_tenure', 'churn_probability', 'customer_lifetime_value'],
      dtype='object')

In [6]:
transactions_df.columns

Index(['customer_id', 'date', 'amount', 'type'], dtype='object')

In [12]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48723 entries, 0 to 48722
Data columns (total 54 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 48723 non-null  int64
 1   age                         48723 non-null  int64
 2   gender                      48723 non-null  object
 3   location                    48723 non-null  object
 4   income_bracket              48723 non-null  object
 5   occupation                  48723 non-null  object
 6   education_level             48723 non-null  object
 7   marital_status              48723 non-null  object
 8   household_size              48723 non-null  int64
 9   acquisition_channel         48723 non-null  object
 10  customer_segment            48723 non-null  object
 11  savings_account             48723 non-null  bool
 12  credit_card                 48723 non-null  bool
 13  personal_loan               48723 non-null  bool
 14  investment_account          48723 non-null  bool
 15  insurance_product           48723 non-null  bool
 16  active_products             48723 non-null  int64
 17  app_logins_frequency        48723 non-null  int64
 18  feature_usage_diversity     48723 non-null  int64
 19  bill_payment_user           48723 non-null  bool
 20  auto_savings_enabled        48723 non-null  bool
 21  credit_utilization_ratio    30460 non-null  float64
 22  international_transactions  48723 non-null  int64
 23  failed_transactions         48723 non-null  int64
 24  tx_count                    48723 non-null  int64
 25  avg_tx_value                48723 non-null  float64
 26  total_tx_volume             48723 non-null  int64
 27  first_tx                    48723 non-null  object
 28  last_tx                     48723 non-null  object
 29  base_satisfaction           48723 non-null  float64
 30  tx_satisfaction             48723 non-null  float64
 31  product_satisfaction        48723 non-null  float64
 32  satisfaction_score          48723 non-null  int64
 33  nps_score                   48723 non-null  int64
 34  last_survey_date            48723 non-null  object
 35  support_tickets_count       48723 non-null  int64
 36  resolved_tickets_ratio      48723 non-null  float64
 37  app_store_rating            48723 non-null  float64
 38  feedback_sentiment          48723 non-null  object
 39  feature_requests            32608 non-null  object
 40  complaint_topics            24377 non-null  object
 41  clv_segment                 48723 non-null  object
 42  monthly_transaction_count   48723 non-null  float64
 43  average_transaction_value   48723 non-null  float64
 44  total_transaction_volume    48723 non-null  int64
 45  transaction_frequency       48723 non-null  float64
 46  last_transaction_date       48723 non-null  object
 47  preferred_transaction_type  48723 non-null  object
 48  first_transaction_date      48723 non-null  object
 49  weekend_transaction_ratio   48723 non-null  float64
 50  avg_daily_transactions      48723 non-null  float64
 51  customer_tenure             48723 non-null  float64
 52  churn_probability           48723 non-null  float64
 53  customer_lifetime_value     48723 non-null  float64
dtypes: bool(7), float64(15), int64(14), object(18)
memory usage: 17.8+ MB

In [14]:
transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3159157 entries, 0 to 3159156
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   customer_id  int64
 1   date         object
 2   amount       int64
 3   type         object
dtypes: int64(2), object(2)
memory usage: 96.4+ MB

In [15]:
customer_df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_id,48723.0,5.502799e+07,2.592111e+07,1.000062e+07,3.270835e+07,5.517447e+07,7.724233e+07,9.999980e+07
age,48723.0,4.454494e+01,1.227684e+01,2.900000e+01,3.000000e+01,4.500000e+01,5.900000e+01,6.000000e+01
household_size,48723.0,3.496234e+00,1.583416e+00,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,1.300000e+01
active_products,48723.0,2.095253e+00,1.178333e+00,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,5.000000e+00
app_logins_frequency,48723.0,2.237617e+01,1.175071e+01,4.000000e+00,1.500000e+01,2.200000e+01,3.000000e+01,1.000000e+02
feature_usage_diversity,48723.0,2.369538e+00,1.744681e+00,0.000000e+00,1.000000e+00,2.000000e+00,4.000000e+00,1.000000e+01
credit_utilization_ratio,30460.0,2.868762e-01,1.600724e-01,1.794056e-04,1.619276e-01,2.658556e-01,3.909798e-01,9.375464e-01
international_transactions,48723.0,4.939146e-01,7.021834e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,6.000000e+00
failed_transactions,48723.0,1.987562e-01,4.439627e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
tx_count,48723.0,6.483913e+01,6.119342e+02,1.000000e+01,1.200000e+01,1.800000e+01,3.500000e+01,7.746500e+04
avg_tx_value,48723.0,3.564852e+06,3.959443e+06,3.182150e+05,1.339114e+06,1.763107e+06,4.658536e+06,5.167030e+07
total_tx_volume,48723.0,2.574728e+08,6.211110e+09,3.182150e+06,2.015845e+07,4.808115e+07,1.204450e+08,1.073087e+12
base_satisfaction,48723.0,8.001457e+00,9.985988e-01,4.250062e+00,7.325575e+00,8.005452e+00,8.676325e+00,1.193721e+01
tx_satisfaction,48723.0,1.772458e-01,2.169632e-01,5.000000e-02,6.000000e-02,9.000000e-02,1.750000e-01,1.000000e+00
product_satisfaction,48723.0,4.736736e-01,2.344574e-01,0.000000e+00,4.000000e-01,4.000000e-01,6.000000e-01,1.000000e+00
satisfaction_score,48723.0,4.162469e+00,5.784730e-01,2.000000e+00,4.000000e+00,4.000000e+00,5.000000e+00,6.000000e+00
nps_score,48723.0,-2.675685e+01,1.256092e+01,-8.000000e+01,-3.400000e+01,-2.800000e+01,-1.900000e+01,2.300000e+01
support_tickets_count,48723.0,9.974550e-01,9.993603e-01,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,7.000000e+00
resolved_tickets_ratio,48723.0,5.061834e-01,4.761853e-01,0.000000e+00,0.000000e+00,5.000000e-01,1.000000e+00,1.000000e+00
app_store_rating,48723.0,4.156302e+00,5.888649e-01,2.000000e+00,4.000000e+00,4.000000e+00,4.500000e+00,5.000000e+00
monthly_transaction_count,48723.0,5.765448e+00,5.096642e+01,1.000000e+00,1.600000e+00,2.000000e+00,3.090909e+00,6.455417e+03
average_transaction_value,48723.0,3.564852e+06,3.959443e+06,3.182150e+05,1.339114e+06,1.763107e+06,4.658536e+06,5.167030e+07
total_transaction_volume,48723.0,2.574728e+08,6.211110e+09,3.182150e+06,2.015845e+07,4.808115e+07,1.204450e+08,1.073087e+12
transaction_frequency,48723.0,1.865574e-01,1.704244e+00,2.785515e-02,4.154303e-02,5.763689e-02,1.031384e-01,2.157799e+02
weekend_transaction_ratio,48723.0,2.828676e-01,1.044426e-01,0.000000e+00,2.142857e-01,2.800000e-01,3.400000e-01,9.090909e-01
avg_daily_transactions,48723.0,1.865574e-01,1.704244e+00,2.785515e-02,4.154303e-02,5.763689e-02,1.031384e-01,2.157799e+02
customer_tenure,48723.0,1.137391e+01,7.195875e-01,4.700000e+00,1.116667e+01,1.163333e+01,1.186667e+01,1.196667e+01
churn_probability,48723.0,3.429222e-01,6.707345e-02,1.143192e-01,3.029380e-01,3.539717e-01,3.927236e-01,5.006407e-01
customer_lifetime_value,48723.0,3.281597e+08,7.926224e+08,0.000000e+00,5.841438e+07,1.296820e+08,2.973559e+08,1.776860e+10

In [16]:
transactions_df.describe()

        customer_id        amount
count  3.159157e+06  3.159157e+06
mean   5.458967e+07  3.970948e+06
std    2.641356e+07  6.978514e+06
min    1.000062e+07  3.640000e+04
25%    3.212021e+07  8.285500e+05
50%    5.492876e+07  1.788300e+06
75%    7.794008e+07  4.184700e+06
max    9.999980e+07  6.897399e+08

In [17]:
customer_df.describe(include = "object").T

                            count unique                     top   freq
gender                      48723      3                  Female  24033
location                    48723     18    Bogotá, Cundinamarca  16967
income_bracket              48723      4                  Medium  19489
occupation                  48723     35             Hairdresser   1456
education_level             48723      4                Bachelor  19685
marital_status              48723      4                  Single  21769
acquisition_channel         48723      4                 Organic  19500
customer_segment            48723      4              occasional  19391
first_tx                    48723    180              2023-01-04   4724
last_tx                     48723    174              2023-12-29   4854
last_survey_date            48723    365              2023-10-08    169
feedback_sentiment          48723      3                Positive  38897
feature_requests            32608     25  Cryptocurrency trading   3336
complaint_topics            24377      5        Customer service   4940
clv_segment                 48723      4                  Bronze  12181
last_transaction_date       48723    174              2023-12-29   4854
preferred_transaction_type  48723      4                Transfer  36954
first_transaction_date      48723    180              2023-01-04   4724

In [19]:
transactions_df.describe(include = "object")

              date      type
count      3159157   3159157
unique         360         4
top     2023-06-20  Transfer
freq          9045   1433963

In [25]:
#Let's check for missing value in the customers dataset first
missing_values = customer_df.isna().sum().to_frame("Missing Values")

missing_values["Percentage"] = round((missing_values["Missing Values"] / len(customer_df) )* 100, 2)
missing_values

                            Missing Values  Percentage
customer_id                              0        0.00
age                                      0        0.00
gender                                   0        0.00
location                                 0        0.00
income_bracket                           0        0.00
occupation                               0        0.00
education_level                          0        0.00
marital_status                           0        0.00
household_size                           0        0.00
acquisition_channel                      0        0.00
customer_segment                         0        0.00
savings_account                          0        0.00
credit_card                              0        0.00
personal_loan                            0        0.00
investment_account                       0        0.00
insurance_product                        0        0.00
active_products                          0        0.00
app_logins_frequency                     0        0.00
feature_usage_diversity                  0        0.00
bill_payment_user                        0        0.00
auto_savings_enabled                     0        0.00
credit_utilization_ratio             18263       37.48
international_transactions               0        0.00
failed_transactions                      0        0.00
tx_count                                 0        0.00
avg_tx_value                             0        0.00
total_tx_volume                          0        0.00
first_tx                                 0        0.00
last_tx                                  0        0.00
base_satisfaction                        0        0.00
tx_satisfaction                          0        0.00
product_satisfaction                     0        0.00
satisfaction_score                       0        0.00
nps_score                                0        0.00
last_survey_date                         0        0.00
support_tickets_count                    0        0.00
resolved_tickets_ratio                   0        0.00
app_store_rating                         0        0.00
feedback_sentiment                       0        0.00
feature_requests                     16115       33.07
complaint_topics                     24346       49.97
clv_segment                              0        0.00
monthly_transaction_count                0        0.00
average_transaction_value                0        0.00
total_transaction_volume                 0        0.00
transaction_frequency                    0        0.00
last_transaction_date                    0        0.00
preferred_transaction_type               0        0.00
first_transaction_date                   0        0.00
weekend_transaction_ratio                0        0.00
avg_daily_transactions                   0        0.00
customer_tenure                          0        0.00
churn_probability                        0        0.00
customer_lifetime_value                  0        0.00

In [26]:
#Let's check for missing value in the transactions dataset first
missing_values = transactions_df.isna().sum().to_frame("Missing Values")

missing_values["Percentage"] = round((missing_values["Missing Values"] / len(transactions_df) )* 100, 2)
missing_values

             Missing Values  Percentage
customer_id               0         0.0
date                      0         0.0
amount                    0         0.0
type                      0         0.0

In [28]:
#let's check for duplicates
customer_df["customer_id"].duplicated().sum()

np.int64(0)

In [30]:
customer_df["customer_id"].nunique()

48723

In [32]:
transactions_df["customer_id"].nunique()

48723

In [34]:
set(customer_df["customer_id"]) - set(transactions_df["customer_id"])

set()

Data Quality Assessment
The project consists of two related datasets:
- Customer Dataset: 48,723 records and 54 variables containing demographic, product ownership, engagement, satisfaction, and customer-level transaction summary information.
- Transaction Dataset: 3,159,157 transaction records containing individual customer transactions.
Overall, the datasets demonstrate a high level of data quality.

In [35]:
transaction_summary = (
    transactions_df
    .groupby("customer_id")
    .agg(
        calculated_tx_count=("amount", "count"),
        calculated_avg_tx_value=("amount", "mean"),
        calculated_total_tx_volume=("amount", "sum")
    )
    .reset_index()
)

transaction_summary.head()

,customer_id,calculated_tx_count,calculated_avg_tx_value,calculated_total_tx_volume
0,10000617,10,6.054025e+06,60540250
1,10003212,11,2.127414e+06,23401550
2,10004554,10,3.575915e+06,35759150
3,10008981,14,1.513354e+06,21186950
4,10011329,19,6.126737e+05,11640800

In [36]:
validation = customer_df.merge(
    transaction_summary,
    on="customer_id",
    how="left"
)

validation.head()

,customer_id,age,gender,location,income_bracket,occupation,education_level,marital_status,household_size,acquisition_channel,customer_segment,savings_account,credit_card,personal_loan,investment_account,insurance_product,active_products,app_logins_frequency,feature_usage_diversity,bill_payment_user,auto_savings_enabled,credit_utilization_ratio,international_transactions,failed_transactions,tx_count,avg_tx_value,total_tx_volume,first_tx,last_tx,base_satisfaction,tx_satisfaction,product_satisfaction,satisfaction_score,nps_score,last_survey_date,support_tickets_count,resolved_tickets_ratio,app_store_rating,feedback_sentiment,feature_requests,complaint_topics,clv_segment,monthly_transaction_count,average_transaction_value,total_transaction_volume,transaction_frequency,last_transaction_date,preferred_transaction_type,first_transaction_date,weekend_transaction_ratio,avg_daily_transactions,customer_tenure,churn_probability,customer_lifetime_value,calculated_tx_count,calculated_avg_tx_value,calculated_total_tx_volume
0,93716481,44,Male,"Pereira, Risaralda",Very High,Engineer,Master,Married,5,Partnership,occasional,True,True,False,False,True,1,15,3,False,False,0.178710,1,0,76,1.679872e+06,127670300,2023-01-05,2023-12-25,9.213372,0.380,0.6,5,-7,2023-12-16,1,0.0,3.5,Neutral,Budgeting tools,NaN,Gold,1.428571,6.054025e+06,60540250,0.030769,2023-12-05,Transfer,2023-01-05,0.300000,0.030769,11.633333,0.362269,3.124148e+08,76,1.679872e+06,127670300
1,49020929,44,Male,"Cali, Valle del Cauca",Medium,Construction Worker,Bachelor,Married,2,Paid Ad,regular,True,False,False,False,False,5,30,0,True,False,NaN,1,0,10,5.445810e+06,54458100,2023-02-05,2023-12-20,6.073093,0.050,0.2,3,-46,2023-05-05,1,1.0,4.0,Positive,NaN,NaN,Bronze,1.571429,2.127414e+06,23401550,0.032934,2023-12-18,Transfer,2023-02-05,0.181818,0.032934,11.500000,0.181790,1.670223e+08,10,5.445810e+06,54458100
2,52690950,45,Male,"Barranquilla, Atlántico",High,Construction Worker,Bachelor,Married,4,Paid Ad,inactive,True,False,False,True,True,3,4,4,True,False,NaN,1,0,10,6.403350e+05,6403350,2023-01-31,2023-12-12,8.198643,0.050,0.6,4,-29,2023-11-16,0,0.0,5.0,Positive,NaN,NaN,Gold,2.500000,3.575915e+06,35759150,0.050000,2023-10-27,Transfer,2023-01-31,0.300000,0.050000,8.766667,0.321265,1.940371e+07,10,6.403350e+05,6403350
3,23199751,45,Male,"Bogotá, Cundinamarca",High,Electrician,High School,Single,2,Referral,inactive,True,False,False,True,False,2,15,4,True,False,NaN,1,1,23,6.601804e+05,15184150,2023-01-10,2023-12-24,7.529577,0.115,0.4,4,-31,2023-05-07,2,0.5,4.5,Positive,"Cryptocurrency trading, Budgeting tools",NaN,Bronze,1.555556,1.513354e+06,21186950,0.047782,2023-11-30,Transfer,2023-01-10,0.142857,0.047782,10.733333,0.336629,3.597811e+07,23,6.601804e+05,15184150
4,61997066,44,Female,"Bogotá, Cundinamarca",Medium,Cleaner,Bachelor,Married,3,Paid Ad,power,True,True,False,False,False,1,19,1,False,False,0.403606,0,0,18,1.457447e+07,262340450,2023-01-05,2023-11-27,6.605627,0.090,0.4,3,-47,2023-09-15,2,1.0,4.0,Positive,International transfers,App performance,Gold,2.111111,6.126737e+05,11640800,0.061889,2023-11-17,Payment,2023-01-05,0.315789,0.061889,11.633333,0.398151,3.046620e+08,18,1.457447e+07,262340450

In [37]:
(validation["tx_count"] == validation["calculated_tx_count"]).value_counts()

True    48723
Name: count, dtype: int64

In [38]:
(validation["total_tx_volume"] == validation["calculated_total_tx_volume"]).value_counts()

True    48723
Name: count, dtype: int64

# Data Discovery Report
## Objective
The objective of this phase was to just try and understand the structure, quality, and the relationships within the customer and transactions datasets before performing any data prepation or analysis
## Dataset Overview
The project consists of two datasets:
* Customer Dataset: 48723 records and 54 variables containing customer demographics, banking product, ownership, digital engagement, customer satisfaction, and precomputed customer metrics
* Transaction Dataset: 3,159,157 transaction records containing transaction dates, amounts, and transaction types.
The two datasets are linked through the **customer_id** field in a one-to-many relationship, where one customer may have multiple transactions.
# Data Quality Assessment
## Customer Dataset
The customer dataset demonstrated excellent overall quality.
Three variables contained missing values:

| Variable	| Missing (%)	| Initial Interpretation |
| ----------| --------------| ------------------------|
| credit_utilization_ratio|	37.48%	|Likely not applicable for customers without a credit card|
| feature_requests	|33.07%	|Likely indicates customers who have not submitted feature | requests
|complaint_topics	|49.97%|	Likely indicates customers who have not lodged complaints|

All remaining variables contained complete observations
## Transaction Dataset
The transaction dataset contained no missing values across any of its variables.
# Data Validation
Several validation checks were performed to assess the integrity of the data:
* Relashionship Integrity - Every transaction record was successfully matched to a customer in the customer dataset.
* Metric Validation - The customer-level summary metrics (tx_count, avg_tx_value, and total_tx_volume) were recalculated from the transaction dataset and matched the values provided in the customer dataset.
# Initial Observations
The following observations were made:
* The dataset follows a relational structure commonly found in banking and financial systems.
* The transaction dataset provides sufficient detail to derive customer-level behavioral metrics.
* Several variables, including Customer Lifetime Value (CLV) and Churn Probability, appear to be derived metrics rather than raw observations.
* Some transaction summary variables appear duplicated under different names and will be reviewed during data preparation.
* Missing values appear to follow logical business rules rather than indicating poor data quality.

# Decisions for the data cleaning phase
Based on the discovery phase, the following actions will be performed during data preparation:
- Convert all date fields to datetime format.
- Validate and remove duplicate records if necessary.
- Preserve missing values that represent "not applicable" rather than data errors.
- Replace missing values in feature requests and complaint topics with meaningful business categories.
- Review duplicated summary variables and determine whether they should be retained or removed.
- Optimize data types where appropriate.
# Conclusions
The datasets demonstrate a high level of completeness and consistency, making them suitable for downstream analysis. Validation checks confirmed the integrity of the relationship between customer and transaction data as well as the accuracy of customer-level transaction summary metrics.